version: "3.7"

services:
  db:
    image: postgres:12.2
    container_name: lunch-time-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"

  server:
    build:
      context: ./server/
    container_name: lunch-time-server
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    volumes:
      - ./server/:/app/
    working_dir: /app
    user: appuser
    command: mvn clean spring-boot:run

  client:
    build:
      context: ./client/
    container_name: lunch-time-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm start
